SQL(Structured Query Language)
sql is a progrmming language used to interact with relational database ke liye use krte hain
htmL=Structured
css=styling
jaavscript=functinaliy
sql=for interaction with database
(schema)) means design of database
(tuple) means row a single row
STEP-1 mysql ka server
step-2 mysql workbench
 // kisi bhi database ko create krne ke liye ham likhte hian 
 CREATE DATABASE db_name; or database akhir me semicolon lagate hain ka naam (isko ham capital me bhi likh skte hain or small me bhi )
 ye insensitive hote hain mtlb capital m ebhi likh skte hian or small me bhi deleet krna ho kuch to 
 DROP DATABASE db_name;
 jis bhi database ke nader table create krna chahate ho to likhte hann 
 
 USE db_name;